// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-wrapper': string;
  'header-middle': string;
}
export const cssExports: CssExports;
export default cssExports;
